# Generated by Django 4.1.5 on 2023-01-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='購入方法')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='イメージ画像')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('isSet', models.BooleanField(default=True, verbose_name='セットフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='在庫数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.product', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_method', to='vending.order_method')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='vending.product')),
            ],
        ),
    ]
